version: '3.6'
services:
  movies-scrapping: 
    image: movieacr.azurecr.io/azf-movie-scrapping
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:80"
      - "7071:7071"
    volumes:
      - ./.env:/home/site/wwwroot/.env
      - ./function_app.py:/home/site/wwwroot/function_app.py